kivanio/brcobranca

lib/brcobranca/boleto/template/rghost.rb
Quando o 'cedente_endereco' não é informado, o atributo 'cedente' estava no lugar errado
Closes #83
=> Ajusta posição do atributo 'cedente'

lib/brcobranca/boleto/base.rb, spec/brcobranca/base_spec.rb
* Melhorada a mensagem de validação da data do documento
* Validações na data do documento quando é enviado em branco ou string (através de API, por exemplo)
Não vejo problema em utilizar o helper `present?` do `active_support` que é uma dependência do `active_model`. Se for remover a dependência do Rails, podemos transformar isso num helper do projeto mais tarde.
=> Validações da data do documento

lib/brcobranca/remessa/cnab400/base.rb, lib/brcobranca/remessa/cnab400/bradesco.rb
Fiz algumas correções nos arquivos de remessa:
Fixed Remessa CNAB400 field 'tipo do registro'
Segundo a documentação o correto é tipo '0'.
Fixed Bradesco Remessa CNAB400 bank code (used only in direct debit).
O código do banco neste caso é requerido apenas se for débito automático.
Fixed Bradesco Remessa CNAB400 field 'nosso_numero' being printed as Fixnum instead of String.
No arquivo estava saindo o código ASCII direto, ao invés do número como uma string.
Fixed Bradesco Remessa CNAB400 field 'endereço débito' to 2 (ignore).
Padrão do campo é 2 (ignorar).
=> Correções nos arquivos de remessa (Base e Bradesco)

Gemfile.lock, brcobranca.gemspec, lib/brcobranca/boleto/bradesco.rb, lib/brcobranca/remessa/cnab400/base.rb, lib/brcobranca/retorno/cnab400/base.rb, spec/brcobranca/boleto/banco_bradesco_spec.rb, spec/brcobranca/retorno/cnab400/base_spec.rb, spec/support/shared_examples/cnab400.rb
Corrigi o cálculo do dígito verificador do Bradesco da agência e conta-corrente (no boleto aparecia 10 ao invés de "P"), e adicionei os testes para esses casos.
Na Remessa, adicionei a gem unidecoder para transformar toda a informação da Remessa em ASCII (alguns bancos tem problemas para determinar o tamanho da linha se tiver acentos). Também padronizei toda a informação da Remessa pra maiúsculo (upcase).
Também fiz uma pequena melhoria no tratamento dos arquivos lidos pela Remessa::Cnab400::Base. Antes dava uma Exception caso o arquivo fosse inválido.
=> Correção do DV de agência de conta corrente do Bradesco. Padronizado Remessa para ASCII upcase.

lib/brcobranca/boleto/base.rb, lib/brcobranca/boleto/template/base.rb, lib/brcobranca/boleto/template/rghost_carne.rb
Permite usar o rghost e rghost_carne ao mesmo tempo.
```ruby
Brcobranca.setup do |config|
config.gerador = :both
end
```
Alterações para uso do carnê, os métodos abaixo que antes usavam o mesmo nome nos 2 templates, passam a ter nomes diferentes.
```ruby
.to >> .to_carne
.lote >> .lote_carne
```
=> Habilita uso de 2 templates simultâneos

lib/brcobranca/boleto/template/rghost_carne.rb
Algumas informações não estavam corretas no carnê.
1. Espécie de documento, estava mostrando espécie (moeda)
2. Espécie, estava mostrando moeda (o número da moeda - 9 e não o símbolo)
=> Rghost carne positions fix

Gemfile.lock, lib/brcobranca.rb, lib/brcobranca/retorno/cnab240/base.rb, lib/brcobranca/retorno/cnab240/caixa.rb, lib/brcobranca/version.rb
I put [# DEPRECATED](https://github.com/kasterweb/brcobranca/blob/master/lib/brcobranca.rb#L120) comment in the Cnab240 class to encourage the users to use ``Brcobranca::Retorno::Cnab240::Base.load_lines`` instead of ``Brcobranca::Retorno::RetornoCnab240.load_lines``. Is that right?
=> Add caixa return file support

.travis.yml, lib/brcobranca/retorno/base.rb, lib/brcobranca/retorno/cnab400/bradesco.rb, spec/brcobranca/retorno/cnab400/bradesco_spec.rb
Este PR ativa o campo código de ocorrência de retorno. Importante informação para cobrança com registro.
Exemplos de tipos de ocorrências conforme documentação Bradesco:
02..Entrada Confirmada
03..Entrada Rejeitada
06..Liquidação normal
=> Ativa cod_de_ocorrencia no retorno bradesco

lib/brcobranca/remessa/pagamento.rb, spec/brcobranca/remessa/pagamento_spec.rb
Corrige https://github.com/kivanio/brcobranca/issues/123
=> Remessa::Pagamento com validação de uf_sacado para apenas 2 dígitos

lib/brcobranca/boleto/template/rghost.rb
Esse PR faz o alinhamento dos valores à direita.
Foi um pedido da homologação do Itaú.
Segue como fica:
=> Alinhamento das informações do boleto a direita

lib/brcobranca/boleto/base.rb, lib/brcobranca/boleto/template/rghost.rb
This PR adds new `demonstrativo` fields to Brcobranca::Boleto::Base as like `instrucao` fields. The attributes are:
```
demonstrativo1
demonstrativo2
demonstrativo3
```
I think this feature is very useful for description of bank billet.
=> Adds demonstrativo fields to Brcobranca::Boleto::Base

lib/brcobranca/boleto/base.rb, spec/brcobranca/boleto/banco_nordeste_spec.rb, spec/brcobranca/boleto/banestes_spec.rb, spec/brcobranca/boleto/bradesco_spec.rb, spec/brcobranca/boleto/hsbc_spec.rb, spec/brcobranca/boleto/itau_spec.rb, spec/brcobranca/boleto/santander_spec.rb, spec/brcobranca/boleto/sicoob_spec.rb, spec/brcobranca/boleto/sicredi_spec.rb, spec/brcobranca/boleto/unicred_spec.rb
Adicionada a validação em Brcobranca::Boleto::Base e alterado os testes para esperar mais 2 erros de validação.
=> Obrigatoriedade do nome e documento do sacado

lib/brcobranca/boleto/base.rb, lib/brcobranca/boleto/caixa.rb, lib/brcobranca/boleto/template/rghost.rb, spec/brcobranca/boleto/caixa_spec.rb
Boletos para CAIXA, outros bancos não testei;
Alteração na LABEL "Carteira" no layout do boleto para imprimir SR ou RG;
O attr :carteira não sofreu alteração para manter a integridade da GEM, permanecendo 1|2
Uso:
@boleto.carteira_label = "RG"
=> Boletos para CAIXA. Imprimir RG ou SR no boleto

lib/brcobranca.rb, lib/brcobranca/boleto/santander.rb, lib/brcobranca/remessa/cnab240/base.rb, lib/brcobranca/remessa/cnab400/banco_brasil.rb, lib/brcobranca/remessa/cnab400/base.rb, lib/brcobranca/remessa/cnab400/bradesco.rb, lib/brcobranca/remessa/cnab400/itau.rb, lib/brcobranca/remessa/cnab400/santander.rb, lib/brcobranca/remessa/pagamento.rb, lib/brcobranca/retorno/base.rb, lib/brcobranca/retorno/cnab240/caixa.rb, lib/brcobranca/retorno/cnab400/banco_brasil.rb, lib/brcobranca/retorno/cnab400/base.rb, lib/brcobranca/retorno/cnab400/bradesco.rb, lib/brcobranca/retorno/cnab400/itau.rb, lib/brcobranca/retorno/cnab400/santander.rb, lib/brcobranca/retorno/retorno_cnab240.rb
Aceitar Juros e Multa em Bradesco, Itaú, Caixa, Banco do Brasil e Santander.
Ler arquivo retorno de Santander e Banco do Brasil.
Preencher o código de motivo das ocorrências na leitura do retorno
=> Suporte a juros, multa, leitura de retorno de bancos cnab400 e código motivo em retorno

lib/brcobranca/remessa/cnab400/sicoob.rb, spec/brcobranca/remessa/cnab240/sicoob_spec.rb, spec/brcobranca/remessa/cnab400/sicoob_spec.rb
Ajusta o calcular do DV da cooperativa Sicoob. A gem está mapeando para X sendo que deveria estar mapeando para 0.
Por exemplo:
Segundo a documentação do banco, a agência '3214' tem DV '0'
=> Corrige calculo de digito verificador de agencia para sicoob

lib/brcobranca/formatacao_string.rb, spec/brcobranca/formatacao_string_spec.rb
Segue teste mostrando o erro e correção para campos que possuem tamanho maior que o limite antes da limpeza e menor que o limite após.
=> Ajustes na função de formatar string para campo de remessa

lib/brcobranca/remessa/cnab400/banco_brasil.rb
Alterações na montagem dos dados para CNAB400 no Banco do Brasil:
- Na montagem do detalhe, estava o valor fixo "01 (Registro de título)" na linha referente ao comando. Adicionada a utilização do atributo "identificacao_ocorrencia" da classe de pagamento para receber a informação e ser possível utilizar os demais comandos do convênio.
- Na montagem do detalhe da multa, para os códigos 0 e 9 havia um return false que quebrava a montagem do arquivo. O código 0 já é tratado na chamada do método, já o código 9, pela documentação do Banco do Brasil, é referente aos casos em que não há cobrança de multa, sendo assim importante ser enviado.
- Ainda na montagem da linha referente a multa, adicionada a utilização do atributo codigo_multa da classe de pagamento onde antes estava fixo o código 2. …
=> Alterações remessa cnab400 do Banco do Brasil

lib/brcobranca/boleto/banco_brasil.rb, spec/brcobranca/boleto/banco_brasil_spec.rb
No processo de homologação do boleto Banco do Brasil foi solicitado a correção do local do pagamento:
Apliquei a alteração apenas para o Banco do Brasil pois não sei confirmar se o mesmo é valido para os outros bancos.
=> Correção do local de pagamento para o Banco do Brasil

.rubocop.yml, lib/brcobranca.rb, lib/brcobranca/boleto/base.rb, lib/brcobranca/boleto/template/base.rb, lib/brcobranca/boleto/template/rghost.rb, lib/brcobranca/boleto/template/rghost_bolepix.rb
Adiciona leitura de EMV para boletos com template de `modelo_generico`. Foi feito apenas para esse modelo por se tratar da minha necessidade atual, por isso `modelo_generico2` e `modelo_carne` ficaram de fora.
Foi testado com um EMV existente e os aplicativos de banco conseguiram ler normalmente. Para fins de visualização, o QRCode do print retorna apenas um texto
=> Possibilitar pagamento via PIX a partir de leitura de EMV

brcobranca.gemspec
Salve @kivanio 
Estive testando a atualização para o Ruby 3.2.0 e pelo o que entendi foi depreciado o comando exists para exist
https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/?rdt=61177
Por isso para evitar erro é necessário usar a biblioteca rghost na versão 0.9.8, onde essa alteração é feita
https://my.diffend.io/gems/rghost/0.9.7/0.9.8
Testei a alteração na API https://github.com/akretion/boleto_cnab_api e parece estar funcionando sem problemas com essa versão.
=> [DEV] Ruby 3.2.0 precisa usar o rghost na versão 0.9.8 

lib/brcobranca/remessa/cnab400/banco_brasil.rb
Arruma o **Número atribuído pela empresa** (Seu Número)  para pegar o valor correto, antes estava sendo atribuído o **nosso_numero** erroneamente.
=> Arrumar o valor do "Seu Número" na Remessa 400 do Banco do Brasil.

lib/brcobranca/boleto/ailos.rb
Altera o comprimento máximo da conta corrente de 7 digitos para 8 dígitos quando for um banco do sistema AILOS.
As novas contas já estão vindo com 8 dígitos.
=> Correção da quantidade de dígitos para a conta corrente AILOS

lib/brcobranca/boleto/template/rghost2.rb
Objetivo dessa PR é a necessidade de adicionar um logo no recibo do Beneficiário, podemos vê o resultado aqui: 
PDF gerado também: 
[boletinho.pdf](https://github.com/kivanio/brcobranca/files/14723930/boletinho.pdf)
=> Adicionando Logo no template Rghost2 no Recibo do Beneficiário 

lib/brcobranca/remessa/cnab240/santander.rb
Objetivo:
Correção do cálculo do Código da Conta Corrente para garantir a geração correta do arquivo REM ao consumir a API.
Detalhes:
O cálculo do Código da Conta Corrente estava apresentando falhas quando baseado no módulo 11. Entretanto, ao remover o cálculo, o arquivo REM é gerado corretamente.
Testes Realizados:
-  Número da conta: 01058941
-  Dígito verificador: 2
Antes: 
Depois:
Durante os testes, o dígito da conta correto está em conformidade como esperado.
cc @marcelsavegnago @antoniospneto
=> [FIX] Santander Remessa 240: Digito da Agência

lib/brcobranca/remessa/cnab400/itau.rb
https://download.itau.com.br/bankline/layout_cobranca_400bytes_cnab_itau.pdf 
Conforme manual, pagina 21 e nota (A)
> (A) Informar a quantidade de dias nas posições 392 a 393. No caso da instrução “42”, o beneficiário
> passa a ter prioridade no recebimento quando o pagador estiver com falência decretada. A
> quantidade de dias será utilizada para as instruções de negativação expressa e protesto, não sendo
> possível informar no arquivo remessa de entrada as instruções de negativação e protesto,
> simultaneamente para o mesmo título. Se forem enviadas as duas instruções, a única a ser
> considerada será a instrução da negativação. Na negativação, caso o campo quantidade de dias seja
> informado com zeros, será considerado o prazo de 2 (dois) dias corridos após o vencimento.
> No caso da …
=> [FIX] itau.rb prazo instrução protesto: 09, 34 e 35

lib/brcobranca/remessa/cnab240/santander.rb, spec/brcobranca/remessa/cnab240/santander_spec.rb
O objetivo desta PR é capturar o código e os dias da baixa/devolução do pagamento.
=> Santander Remessa 240: Adiciona código e dias da baixa/devolução

lib/brcobranca/boleto/base.rb, lib/brcobranca/boleto/template/rghost_bolepix.rb
Adiciona a possibilidade de preencher abatimentos e descontos nos campos devidos do template genérico.
Foi alterado apenas em `Brcobranca::Boleto::Template::RghostBolepix` por ser o que nós usamos aqui e ser o template que contribuímos da outra vez.
=> Adiciona a renderização dos valores de descontos/abatimentos nos campos devidos do boleto.
